### ISSUE TITLE
Simplify CSS

### ISSUE THREAD

**Issue by melissamcewen** [Nadia3839/prj-rev-bwfs-dasmoto#3]
The way I write CSS is:

### Step 1: Look for things that apply to the entire page. 

In this case it's the Helvetica font. I can make that the font for everything and then get rid of a bunch of other lines of css
```css
body {
  font-family: "Helvetica", sans-serif;
}
```

These lines can then be removed
https://github.com/Nadia3839/prj-rev-bwfs-dasmoto/blob/master/Dasmotos%20A%26C/resources/css/index.css#L11
https://github.com/Nadia3839/prj-rev-bwfs-dasmoto/blob/master/Dasmotos%20A%26C/resources/css/index.css#L2
https://github.com/Nadia3839/prj-rev-bwfs-dasmoto/blob/master/Dasmotos%20A%26C/resources/css/index.css#L30

## Step 2: Style the basic HTML elements

Like `<h1>` and `<p>` and `<h2>`. You already did a great job with this! ⭐️ 

## Step 3: Target any specific exceptions
These are HTML elements that are a little different from the rest. I add a class to these so I can target them. You also did a great job with this! Though you can simplify further by just using the class. 
https://github.com/Nadia3839/prj-rev-bwfs-dasmoto/blob/master/Dasmotos%20A%26C/resources/css/index.css#L17-L27
```css
.brushes {
  background-color: mediumspringgreen;
}

.frames {
  background-color: lightcoral;
}

.paint {
  background-color: skyblue;
}
```

I also recommend keeping all classes lowercase. It technically works as upper or mixed case but may cause issues once you start working with Javascript.
